#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Tomoya Suzuki

import sys


mid , ave , x, num= 0.0, 0.0, 0.0, 0
des =[]                                #空のリスト作成

for n in sys.stdin:                    #１行ずつファイルから読み込み 
    x += float(n)
    des.append(float(n))               #append関数でリストの末尾にnを追加
    num += 1

ave = x/num                            #平均計算

for i in range(num):                   #range関数で０～num-1までの数列を作る
    for j in range(num-(i+1)):         #降べきの順に変換　バブルソート
        if des[j] > des[j+1]:
            a = des[j]
            des[j] = des[j+1]
            des[j+1] = a

print(des[0:num])                      #降べきの順を出力
    
if num%2 == 0:                         #中央値の計算　偶数奇数で分ける
    n = num/2 - 1                      #リストの最初は0なので１ずらす
    m = num/2
    mid = (des[int(n)]+des[int(m)])/2

else:
    p = num/2 - 0.5
    mid = des[int(p)]

print(" ")
print("中央値:" + str(mid))             #strコマンドで文字列に変換
print("平均値:" + str(ave))
print("最大値:" + str(des[num-1]))
print("最小値:" + str(des[0]))
