#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Tomoya Suzuki
# SPDX-License-Identifier: BSD-3-Clause

import sys


def tonum(s):                         #def で関数を定義　tonumという関数を作る
    try:                              #例外処理　intが無理ならfloatに変換    
        return int(s)
    except:
        return float(s)


mid , ave , x, dissum, disper, num= 0.0, 0.0, 0.0, 0.0, 0.0, 0
des =[]                                #空のリスト作成

for n in sys.stdin:                    #１行ずつファイルから読み込み 
#    n = n.rstrip()                     #右側の（）内の文字を除去
    x += tonum(n)
    des.append(tonum(n))               #append関数でリストの末尾にnを追加
    num += 1

for i in range(num):                   #range関数で０～num-1までの数列を作る
    for j in range(num-(i+1)):         #降べきの順に変換　バブルソート
        if des[j] > des[j+1]:
            a = des[j]
            des[j] = des[j+1]
            des[j+1] = a
    
ave = x/num                            #平均計算

for m in range(num):                   #分散
    dissum += (des[m] - ave)**2        #べき乗は**

disper = dissum/num

if num%2 == 0:                         #中央値の計算　偶数奇数で分ける
    n = num/2 - 1                      #リストの最初は0なので１ずらす
    m = num/2
    mid = (des[int(n)]+des[int(m)])/2

else:
    p = num/2 - 0.5
    mid = des[int(p)]

print(str(des[0::]) + "   " + "中央値:" + str(mid) + "  平均値:" + str(ave) + "　分散:" + str(disper) + "  最大値:" + str(des[num-1]) + "  最小値:" + str(des[0]))
#strコマンドで文字列に変換

