#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Tomoya Suzuki

import sys

mid , ave ,num, x= 0.0, 0.0, 0.0, 0.0
for n in sys.stdin:
    x += float(n)
    num += 1
    des[int(num)] = float(n)

for i in range(int(num)):
    print(des[int(num)])    

ave = x/num

print(ave)
