#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Tomoya Suzuki

import sys

mid , ave , x, num= 0.0, 0.0, 0.0, 0
des =[]
for n in sys.stdin:
    x += float(n)
    des.append(float(n))
    num += 1

ave = x/num

for i in des:
    print(i)
    

print(ave)
