#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Tomoya Suzuki

import sys


def tonum(s)
    try:
        return int(s)
    except:
        ans += float(s)

ans = 0

for line in sys.stdin:
    line = line.rstrip()
        ans += tonum(line)

print(ans)
